version: '3.9'

services:
    backend:
        build: .
        volumes:
            - ..:/home/animmendation/tcc_animmendation/backend
            - ~/.ssh:/home/animmendation/.ssh
            - datasets:/home/animmendation/tcc_animmendation/backend/datasets
        ports:
            - 4000:4000
        command: tail -f /dev/null
        extra_hosts:
            - host.docker.internal:host-gateway
        env_file: ../.env
        tty: true
        depends_on:
            redis:
                condition: service_started
            db:
                condition: service_healthy

    db:
        image: postgres:15
        ports:
            - ${DB_PORT:-5432}:5432
        environment:
            POSTGRES_USERNAME: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        volumes:
            - dbdata:/var/lib/postgresql/data
            - datasets:/datasets
        healthcheck:
            test: pg_isready -U $$POSTGRES_USERNAME  -d $$POSTGRES_DB
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 5s
    
    translator:
        build:
            dockerfile: Dockerfile.libretranslate
            args:
                models: en,pt
        restart: unless-stopped
        ports: 
            - 5000:5000
        command: --disable-files-translation --disable-web-ui
        

    redis:
        image: redis/redis-stack-server:latest
        ports:
            - ${REDIS_HOST:-6379}:6379
        environment:
            REDIS_ARGS: "--requirepass ${REDIS_PASSWORD}"

volumes:
    dbdata:
    datasets:


